### ISSUE TITLE
Read1/Reads2 using  in Kraken2Uniq

### ISSUE THREAD

**Issue by oyxf** [Yunuuuu/rsahmi#1]
Very wonderful works! I have a question to ask you for help, when using Kraken2Uniq to mapping , which reads should be choose for 10x genomics data? Both or only Read2?

**Comment by Yunuuuu** [comment]
Sorry, I'm not an export of this algorithm, but provide a convient way to run the process. You'd better to ask this in the original repo - https://github.com/sjdlabgroup/SAHMI. But in this way, from my point of view, I'll use both reads.

**Comment by oyxf** [comment]
OK.Thank you for your reply!

**Comment by Yunuuuu** [comment]
Now, I prefer using read2 only since read1 only contain barcode and umi.

**Comment by oyxf** [comment]
Yeah, I use read2 for kraken2uniq  in my analysis pipeline finally, and it will be faster in speed.
