### ISSUE TITLE
unused argument (after = "taxid") for data.table::setcolorder 

### ISSUE THREAD

**Issue by oyxf** [Yunuuuu/rsahmi#3]
when i run rsahmi::run_blsd, the error appeared as above . The version for data.table  package is ? My version is 1.14.8

**Comment by Yunuuuu** [comment]
Thank you for the report. The data.table I used is version 1.14.9. I'll add the requierement in the DESCRIPTION file

**Comment by Yunuuuu** [comment]
Please update to the development version in the github

**Comment by oyxf** [comment]
Thank you very much!
